import { execFile } from "node:child_process";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import { UserError } from "./types";

// Open-source ProGuard: renames classes/methods/fields and shrinks dead code so a distributed
// plugin jar is expensive to reverse-engineer. See the java-plugin-obfuscation repo for the
// reasoning behind every rule below. This is not encryption; it raises the cost, it doesn't lock.

const PROGUARD_VERSION = process.env.PROGUARD_VERSION || "7.6.1";
const VENDOR_JAR = path.resolve(process.cwd(), "vendor", "proguard", "lib", "proguard.jar");
const DICT = path.resolve(process.cwd(), "obfuscation", "proguard-dict.txt");
const JDK_MODULES = ["java.base", "java.sql", "java.naming", "java.logging", "java.desktop", "java.management", "java.xml"];

export const MAX_JAR_BYTES = 150 * 1024 * 1024; // 150 MB

/** Absolute path to a usable proguard.jar, or null if none is installed yet. */
function findProguardJar(): string | null {
  const envJar = process.env.PROGUARD_JAR;
  if (envJar && fs.existsSync(envJar)) return envJar;
  if (fs.existsSync(VENDOR_JAR)) return VENDOR_JAR;
  return null;
}

/** Downloads ProGuard into ./vendor/proguard on first use (unless PROGUARD_AUTODOWNLOAD=false). */
async function ensureProguardJar(): Promise<string> {
  const existing = findProguardJar();
  if (existing) return existing;
  if (process.env.PROGUARD_AUTODOWNLOAD === "false") {
    throw new UserError("ProGuard isn't installed. Run `node scripts/install-proguard.mjs` on the server first.");
  }
  const url = `https://github.com/Guardsquare/proguard/releases/download/v${PROGUARD_VERSION}/proguard-${PROGUARD_VERSION}.zip`;
  const dest = path.dirname(path.dirname(VENDOR_JAR)); // vendor/proguard
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "proguard-dl-"));
  try {
    const res = await fetch(url);
    if (!res.ok || !res.body) throw new UserError(`Couldn't download ProGuard (HTTP ${res.status}). Install it manually with \`node scripts/install-proguard.mjs\`.`);
    const zip = path.join(tmp, "proguard.zip");
    await pipeline(Readable.fromWeb(res.body as Parameters<typeof Readable.fromWeb>[0]), fs.createWriteStream(zip));
    const extract = path.join(tmp, "x");
    fs.mkdirSync(extract, { recursive: true });
    execFileSync("unzip", ["-q", zip, "-d", extract]);
    const inner = path.join(extract, `proguard-${PROGUARD_VERSION}`);
    const src = fs.existsSync(inner) ? inner : extract;
    fs.rmSync(dest, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.renameSync(src, dest);
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
  const jar = findProguardJar();
  if (!jar) throw new UserError("ProGuard installed but proguard.jar is still missing. Try `node scripts/install-proguard.mjs --force`.");
  return jar;
}

const MAIN_RE = /^\s*main\s*:\s*["']?([A-Za-z_$][\w$]*(?:\.[A-Za-z_$][\w$]*)*)["']?\s*$/m;
const NAME_RE = /^\s*name\s*:\s*["']?([^"'\n#]+?)["']?\s*$/m;

/** Reads one text entry from a jar with the system `unzip`, or null if it isn't there. */
function readJarEntry(jar: string, entry: string): string | null {
  try {
    return execFileSync("unzip", ["-p", jar, entry], { maxBuffer: 8 * 1024 * 1024 }).toString("utf8");
  } catch {
    return null;
  }
}

interface PluginMeta {
  main: string | null;
  name: string | null;
}

function readPluginMeta(jar: string): PluginMeta {
  const yml = readJarEntry(jar, "plugin.yml") || readJarEntry(jar, "paper-plugin.yml") || "";
  return { main: MAIN_RE.exec(yml)?.[1]?.trim() || null, name: NAME_RE.exec(yml)?.[1]?.trim() || null };
}

function buildConfig(meta: PluginMeta): string {
  const lines = [
    "# Generated by Xkixos Licensing — see the java-plugin-obfuscation repo for the why.",
    "-dontoptimize",
    "-dontusemixedcaseclassnames",
    "-useuniqueclassmembernames",
    "-allowaccessmodification",
    "-repackageclasses ''",
    "-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,SourceFile,LineNumberTable",
    "-dontnote **",
    "-dontwarn **",
    "-ignorewarnings",
    "",
    "# Event handlers are discovered by @EventHandler, not by name: renameable but never removed.",
    "-keepclassmembers,allowobfuscation class * {",
    "    @org.bukkit.event.EventHandler <methods>;",
    "}",
    "",
    "# Enum constant names are written to config/DB and read back via valueOf — keep them verbatim.",
    "-keepclassmembers enum * {",
    "    public static **[] values();",
    "    public static ** valueOf(java.lang.String);",
    "}",
    "",
    "# Java serialization plumbing is invoked reflectively by the JDK.",
    "-keepclassmembers class * implements java.io.Serializable {",
    "    static final long serialVersionUID;",
    "    private void writeObject(java.io.ObjectOutputStream);",
    "    private void readObject(java.io.ObjectInputStream);",
    "    java.lang.Object writeReplace();",
    "    java.lang.Object readResolve();",
    "}",
    "",
  ];
  if (meta.main) {
    lines.push(
      "# plugin.yml main class: Bukkit instantiates it from the name string, so the name must survive.",
      `-keep public class ${meta.main} {`,
      "    public <init>(...);",
      "    public void onLoad();",
      "    public void onEnable();",
      "    public void onDisable();",
      "}",
      "",
    );
  }
  return lines.join("\n") + "\n";
}

export interface ObfuscateResult {
  jar: Buffer;
  meta: PluginMeta;
  log: string;
}

/**
 * Obfuscates a Bukkit/Paper plugin jar with open-source ProGuard and returns the rewritten jar.
 * Set LIBRARY_JARS (path-separator list) or PAPER_API_JAR to feed ProGuard the server API for the
 * strongest, safest result; without them it falls back to -dontwarn and still produces a working jar.
 */
export async function obfuscateJar(input: Buffer): Promise<ObfuscateResult> {
  if (input.length === 0) throw new UserError("The uploaded file is empty");
  if (input.length > MAX_JAR_BYTES) throw new UserError(`Jar is too large (max ${Math.round(MAX_JAR_BYTES / 1024 / 1024)} MB)`);
  // A jar is a zip: it starts with "PK".
  if (input[0] !== 0x50 || input[1] !== 0x4b) throw new UserError("That doesn't look like a .jar file");

  const proguardJar = await ensureProguardJar();
  const work = fs.mkdtempSync(path.join(os.tmpdir(), "xkl-obf-"));
  const inJar = path.join(work, "in.jar");
  const outJar = path.join(work, "out.jar");
  const confFile = path.join(work, "proguard.conf");

  try {
    fs.writeFileSync(inJar, input);
    const meta = readPluginMeta(inJar);
    if (!meta.main) {
      throw new UserError("Couldn't read a main class from plugin.yml. This tool obfuscates Bukkit/Paper plugin jars.");
    }
    fs.writeFileSync(confFile, buildConfig(meta));

    const args = [
      "-jar",
      proguardJar,
      "@" + confFile,
      "-injars",
      inJar,
      "-outjars",
      outJar,
    ];
    for (const mod of JDK_MODULES) {
      args.push("-libraryjars", `<java.home>/jmods/${mod}.jmod(!**.jar;!module-info.class)`);
    }
    const extraLibs = [process.env.PAPER_API_JAR, ...(process.env.LIBRARY_JARS || "").split(path.delimiter)].filter(Boolean) as string[];
    for (const lib of extraLibs) {
      if (fs.existsSync(lib)) args.push("-libraryjars", lib);
    }
    if (fs.existsSync(DICT)) {
      args.push("-classobfuscationdictionary", DICT, "-packageobfuscationdictionary", DICT, "-obfuscationdictionary", DICT);
    }

    const log = await runProguard(args);
    if (!fs.existsSync(outJar)) {
      throw new UserError("Obfuscation produced no output. " + lastErrorLine(log));
    }
    return { jar: fs.readFileSync(outJar), meta, log };
  } finally {
    fs.rmSync(work, { recursive: true, force: true });
  }
}

function lastErrorLine(log: string): string {
  const line = log.split("\n").reverse().find((l) => /error|exception|unknown option|can't|cannot/i.test(l));
  return line ? line.trim() : "Check the server logs for details.";
}

function runProguard(args: string[]): Promise<string> {
  return new Promise((resolve, reject) => {
    // ProGuard's own proxy system properties can interfere; a clean JAVA_TOOL_OPTIONS keeps logs tidy.
    const env = { ...process.env };
    delete env.JAVA_TOOL_OPTIONS;
    execFile(
      "java",
      args,
      { env, maxBuffer: 32 * 1024 * 1024, timeout: 5 * 60_000 },
      (err, stdout, stderr) => {
        const log = `${stdout || ""}\n${stderr || ""}`.trim();
        if (err) {
          if ((err as NodeJS.ErrnoException).code === "ENOENT") {
            return reject(new UserError("Java isn't installed on the server. ProGuard needs a JDK (java) on PATH."));
          }
          return reject(new UserError("ProGuard failed: " + lastErrorLine(log)));
        }
        resolve(log);
      },
    );
  });
}
